import os
import datetime
import re
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# thanks to reddit user u/yawpitch for natural sort regular expression
def natural_sort_key(value):
    return tuple(int(s) if s.isdigit() else s for s in re.split("(\d+)",value ))


def plot(test=False):

    """
    Plots data from files in CSVs folder

    Args:
        test (bool):
        because real csv files scraped from follet aspen and test csv files generated by generator.py are
        named using different formats, plot() must which type you are acting on.
    """
    dates = []
    grades = {}

    first_iteration = True
    #os.scandir() reads in an arbitrary order. we use sorted with a lambda function as the key to solve this
    for csv in sorted(os.scandir("CSVs"), key=lambda e: natural_sort_key(e.name)):

        data = pd.DataFrame.from_csv(csv.path) 

        date = csv.path.split('/')[1].split('.')[0] #CSVs/12-12-12.csv -> 12-12-12
        dates.append(date)

        # the first file will be used as the template to create the dict's key value pairs
        if first_iteration:
            for index, row in data.iterrows():
                if not test:
                    # create a new key value pair in grades with key as course name and value as a list of ints
                    # splitting at space and taking first value to disregard letter 
                    grades[row['Description']] = [row['Term Performance'].split(' ')[0]]
                else:   
                    grades[row['Description']] = [row['Term Performance']] # test data has no letters
            first_iteration = False
        
        # all other files can be added staright to dict
        else:
            for index, row in data.iterrows():
                if not test:
                    # add grade to corresponding list
                    # splitting at space and taking first value to disregard letter 
                    grades[row['Description']].append(row['Term Performance'].split(' ')[0])
                else:
                    grades[row['Description']].append(row['Term Performance']) # test data has no letters

    print(dates)
    print(grades)

    graph = plt.figure(figsize=(10, 5)) # create a figure with dimensions 10 x 5 inches
    image = graph.add_subplot(111) #in the middle

    #date formatting
    dates = [datetime.datetime.strptime(d,'%m-%d').date() for d in dates]
    graph.gca().xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
    graph.gca().xaxis.set_major_locator(mdates.DayLocator())

    legend = []
    for key in grades:
        image.plot(dates, grades[key])
        legend.append(key)
    image.legend(legend, loc='upper left')
    plt.show()

plot(test=True)